# Generated by Django 5.2.7 on 2025-10-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_task_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
    ]
